[project]
name = "mangabz-downloader"
version = "1.0.0"
description = "Download manga from Mangabz."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
